export class BookUpdateModel{
    searchNum:string;
    isbn:string;
    bookName:string;
    author:string;
    content:string;
    summary:string;
    totalpage:any;
    language:string;
    publishPlace:string;
    publishtime:string;
    updatetime:string;
    typeName:string;
    owner:string;
    useNum:string;
    remark:string;
    picture:string;
    location:string;
    bookNum:number;
}